### ISSUE TITLE
Snipper's To-Do List

### ISSUE THREAD

**Issue by ImSnipper** [GorilloCraft/Server#108]
Opening this so that I can keep track of what I want to complete in the coming days:

- [x] Update the head board/head menu with the 9 new heads (First priority in the morning)
- [x] Add leave messages for all players (not just staff when they vanish)
- [x] Add /hat to donator rank (Merchant+)
- [x] Add more BP Tiers
- [x] Get the drip leaf event moved to Survival
- [x] Organize a time for Eddie & Griff to chat about bosses
- [ ]

**Comment by MelodyMcKenna** [comment]
Hey Snipper, can we also enable Death Messages in the survival world chat, please?

**Comment by ImSnipper** [comment]
> Hey Snipper, can we also enable Death Messages in the survival world chat, please?

showDeathMessages: true - I feel like I've tried in the past to enable death messages...I just did it again - hopefully this works....

**Comment by MelodyMcKenna** [comment]
> showDeathMessages: true - I feel like I've tried in the past to enable death messages...I just did it again - hopefully this works....

Sorry to say, but death messages still do not appear in chat.

**Comment by ImSnipper** [comment]
Death messages are now working!

Tested and fully functional!
