### ISSUE TITLE
Snipper's To-Do List 11/28/22

### ISSUE THREAD

**Issue by ImSnipper** [GorilloCraft/Server#158]
Snipper's To-Do list for 11/28/22

- [ ] Update the head shop
- [ ] Load up, and test the "Advent Calendar" plugin
- [ ] Create rewards for advent calendar
